import PropTypes from "prop-types";
import Card from "../components/card";
import Header from "../components/header";
import data from "../data/contact/contact.json";
import styles from "../styles/grid.module.css";
import Head from "next/head";
import Footer from '../components/footer'

const Grid = ({ children }) => <div className={styles.grid}>{children}</div>;
Grid.propTypes = {
  children: PropTypes.node.isRequired,
};

const ContactPage = () => (
  <div>
    <Head>
      <title>Contact | Domain Square +</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/d2s-logo.png" />
    </Head>
    <Header />
    <div className="text-gray-100 my-12 sm:mt-4 mt-20 sm:px-32 px-10">
      <h1 className="about text-center sm:text-6xl text-5xl font-semibold mb-16">Contact Us</h1>
      {data.map((contact, index) => (
        <div key={index}>
          <Grid>
            {contact.contacts.map((member) => (
              <Card key={member.name}>
                <div>
                  <div className="sm:text-3xl text-2xl font-semibold">{member.name}</div>
                  <div className='text-md'>{member.role}</div>
                </div>
                <p className="mt-4 mb-0">
                  <a href={`MAILTO:${member.email}`} className='footer-links' >{member.email}</a>
                </p>
              </Card>
            ))}
          </Grid>
        </div>
      ))}
    </div>
    <div className='contact-footer'>
      <Footer />
    </div>
  </div>
);

export default ContactPage;
