import Header from "../components/header";
import styles from "../styles/grid.module.css";
import PropTypes from "prop-types";
import data from "../data/members/members.json";
import Card from "../components/card";
import Head from "next/head";
import Footer from '../components/footer'

const Grid = ({ children }) => <div className={styles.grid}>{children}</div>;
Grid.propTypes = {
  children: PropTypes.node.isRequired,
};

const MembersPage = () => (
  <div>
    <Head>
      <title>Members | Domain Square +</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/d2s-logo.png" />
    </Head>
    <Header />
    <div className="text-gray-100 my-12 sm:mt-4 mt-20 sm:px-32 px-10">
      <h1 className="about text-center sm:text-6xl text-5xl font-semibold">Members</h1>
      {data.map((grade, index) => (
        <div key={index}>
          <h2 className="my-10 sm:text-3xl text-2xl">{`${grade.year}`}</h2>
          <Grid>
            {grade.members.map((member) => (
              <Card key={member.name}>
                <div className="sm:text-3xl text-2xl font-semibold">{member.name}</div>
                <div className='text-md'>{member.role}</div>
              </Card>
            ))}
          </Grid>
        </div>
      ))}
    </div>
    <Footer />
  </div>
);

export default MembersPage;
